### ISSUE TITLE
ETH2x-FLI Product Dashboard

### ISSUE THREAD

**Issue by josephd8** [SetProtocol/index-coop-analytics#18]

**Comment by josephd8** [comment]
https://docs.google.com/spreadsheets/d/1mbJ7r0egq_DpJPgzMJU-GSzMMwQW6Tva1t6JHamZ6U4/edit?ts=60994032#gid=0

**Comment by jorijnsmit** [comment]
Ready to help!

**Comment by Sidheartx** [comment]
You can assign me here as well!

**Comment by josephd8** [comment]
@jorijnsmit @Sidheartx I know there is still some work to do on the "user analytics" of ETH2x (same with BTC 2x), but I think we this issue was meant to be a broad pass at getting the ETH2x-FLI dash build, and we are in a good spot there. I want to close out this issue, and then open new issues so we have the following:

- BTC2x-FLI Dashboard (replicating everything we have in ETH2x dash for BTC2x, this is already opened)
- FLI User Analytics - set of metrics to go in FLI product dashboards (so will be implemented in both ETH2x and BTC2x) to better understand who is using the products and how they are using them

What do you think? Would those two issues encompass the work we currently have to do?

**Comment by Sidheartx** [comment]
Sounds good! There are also some changes/filtering that needs to be done to ETH2x FLI queries (Mainly Costs related) as ETH2x and BTC2x data is on same tables now. Should we have a separate issue for those?

**Comment by josephd8** [comment]
Ya, we can put that as a separate issue - is it just the cost queries that need updated? I will add these new issues and then you can update them with any other information that you have.

**Comment by Sidheartx** [comment]
yeah, just the costs. Revenue etc for both are independent. I'll put the notes in the new issue

**Comment by josephd8** [comment]
Ok - new issues have been added. Great work on all this @jorijnsmit @Sidheartx ! Going to close this issue out.
