### ISSUE TITLE
NAVs vs Market Prices

### ISSUE THREAD

**Issue by josephd8** [SetProtocol/index-coop-analytics#22]
We need to build views that track the NAVs vs Market Prices for each of our index products, starting with DPI and MVI. It would be great to build two separate views, one that is on an hourly basis over a longer time period, and one that is on a minute basis over the past day or so.

**Comment by josephd8** [comment]
So in order to do this, we need to know the nominal amount of each token within 1 DPI. If we have the nominal amounts of each token in 1 DPI, then we can sum up those amounts * their token price to get a NAV (Net Asset Value). We then plot that against the market price of DPI

I think the way that we can get the nominal amount is by evaluating the mint events

So when DPI is minted, the equivalent amounts of the underlying tokens have to be sent to the contract

You can see mint events with this query:

```
SELECT
    *
FROM setprotocol_v2."BasicIssuanceModule_evt_SetTokenIssued"
WHERE "_setToken" IN ('\x1494ca1f11d487c2bbe4543e90080aeba4ba3c2b')
```

Then, if you look at one of those transactions:

```
SELECT
    *
FROM erc20."ERC20_evt_Transfer"
WHERE evt_tx_hash = '\x4836e3a0d98c5586d6e1b7aa58eeeee2dfdac0fc2e9d13d2c48a9e8910bf061c'

```
you can see all the token transfers for that transaction - essentially you can map the token amounts that were transferred to the amount of DPI that was minted - we should find a stable amount of each token per 1 DPI

Once we have that, we can then calculate the NAV price and plot against the market price.

**Comment by Lorengo** [comment]
I'm working on it!
