### ISSUE TITLE
Growth KPIs Dashboard

### ISSUE THREAD

**Issue by josephd8** [SetProtocol/index-coop-analytics#29]
Growth KPIs (week / week, month / month, quarter / quarter, etc) do a better job in many instances of illuminating and explaining what has been happening with a product over a given time period. Currently, these metrics are not calculated outright in any of our dashboards, but rather users are left to use the numbers in the KPI dashboard to calculate them.

This dashboard will contain growth KPI metrics for our products, as well as tables or ease of copying and using the metrics in other content or discussions. 

Also will attempt to create summary tables for our products similar to what is found in the 'Dashboard (Beta)' tab of this worksheet: https://docs.google.com/spreadsheets/d/1ImauyHRrqD7hw1CxD9MYd3r7sD28PG2PmAkUAlsY04w/edit#gid=1933881405

**Comment by rulonudall** [comment]
working on this

**Comment by jackiep00** [comment]
Alright I'll take a crack at this! looks like there's a lot of requests so will probably break it down into multiple PRs

**Comment by jackiep00** [comment]
@josephd8 questions for you - there appear to queries that you made that seem to address the requests above. Do they generally work? Should I just refactor them to make them more generalizable for some list of tokens that's easier to maintain when there are new products / update to include existing products?
1. For "Index Coop Address Exposure (All products)": https://duneanalytics.com/queries/25282
2. "Index Coop Total Supply": https://duneanalytics.com/queries/25300
3. "Mint Volume": https://duneanalytics.com/queries/25370
4. "Trading Volume": https://duneanalytics.com/queries/25372

**Comment by josephd8** [comment]
@jackiep00 so the idea is that those queries currently contain absolute growth, but not week over week (w/w) or month over month (m/m). So your last question hits it - the request is to use these base queries to create period on period growth metrics - does that make sense?

**Comment by jackiep00** [comment]
got it - that's quite straightforward. Thanks!

**Comment by josephd8** [comment]
@ehrena can you make a comment here so I can assign this issue to you?

**Comment by ehrena** [comment]
On it @josephd8

**Comment by ehrena** [comment]
Updated the PR for this issue here: https://github.com/SetProtocol/index-coop-analytics/pull/52
Dashboard sandbox here: https://duneanalytics.com/ehrena/AndrewIndexSampleDashboard
