### ISSUE TITLE
Uniswap v3

### ISSUE THREAD

**Issue by josephd8** [SetProtocol/index-coop-analytics#31]
We need to add uniswap v3 liquidity pools for our products - across all queries.

**Comment by josephd8** [comment]
Initially, there is just one pool that has significant volume on Uniswap v3: https://info.uniswap.org/#/pools/0x151ccb92bc1ed5c6d0f9adb5cec4763ceb66ac7f

Going to get this pool added to the ETH2x-FLI Supply Breakdown and Index Coop Supply Breakdown queries - will provide a roadmap for future queries that need to incorporate Uniswap v3.

**Comment by josephd8** [comment]
Also need to add individual liquidity providing positions on uniswap v3 to correctly assess exposure to our assets. We can start with ETH2x-FLI, given that it is the only product that has significant volume currently.

**Comment by deepsp94** [comment]
Picking this up!
