### ISSUE TITLE
DPI & MVI Market Capture

### ISSUE THREAD

**Issue by josephd8** [SetProtocol/index-coop-analytics#42]
This issue comes from a conversation in the #analytics channel with Mr Madila:

"Whilst I'm here... ^ Please see column H [in the DPI analysis tab] (https://docs.google.com/spreadsheets/d/1ImauyHRrqD7hw1CxD9MYd3r7sD28PG2PmAkUAlsY04w/edit#gid=1735861249) aka something I am calling "Market Capture". It's basically the total DPI or MVI market cap etc / by the total market caps of their respective constituents. Should be a fairly easy one to do on dune. It's essentially a proxy to unit supply but is just another way of looking at how well we are doing filtering out market noise and price volatility etc." (https://discord.com/channels/762061559744299010/791003550242832406/852123393071382538)

We need to build out this metric for DPI and MVI and add them to their respective dashboards.

**Comment by Lorengo** [comment]
I'll take it

**Comment by josephd8** [comment]
@Lorengo have you started working on this issue? Should I move it to 'in progress'?

**Comment by josephd8** [comment]
@Lorengo - I know we are blocked from completing this on Dune - but would you be able to do this in either R or Python using the CoinGecko API?
