### ISSUE TITLE
Evaluate Uniswap v3 to lever/delever FLI products

### ISSUE THREAD

**Issue by josephd8** [SetProtocol/index-coop-analytics#44]
https://discord.com/channels/762061559744299010/764244972484296755/851893218361737286
https://discord.com/channels/762061559744299010/764244972484296755/851935796668006420

"Would anyone be interested in taking on this task? You would need to pull historic V3, V,2 and Sushi data from The Graph and compare the price impact of 500 ETH, 1000 ETH, 2000 ETH trades; as well as 20 WBTC, 50 WBTC, 100 WBTC trades.

Relevant trading pairs here are ETH:USDC and WBTC:USDC."

**Comment by josephd8** [comment]
After discussing with a broader group, we need to develop views looking at the historical price impacts of larger trades on v2 and v3 since v3 launched (large trade levels being detailed in the comment above). 

If we have the swap data, and we can compare that to the pool liquidity data (how much liquidity / how much of each token) at the time of the swap, we should be able to calculate the price impact (https://dailydefi.org/articles/price-impact-and-how-to-calculate/). This is definitely true for v2. However, it is still unclear if we can take this approach for v3. It does not seem like we can use the same constant product formula with v3 given the way concentrated liquidity works - I have not been able to find documentation on how to calculate price impact on v3.

We should progress with the assumption that we will figure out the price impact calculation for v3. So the required data we need to gather from either The Graph or Dune:

- [ ] swaps in ETH:USDC and WBTC:USDC pools since May 5 on v2 and v3
- [ ] hourly (or by minute?) pool liquidity amounts (and token amounts)
          *for v3 we will need to get liquidity across all "ticks" I believe - I am not sure if the price impact calculation will require 
            us to traverse across ticks

Once we have these, we can join them and then use whatever price impact calculation. We can then create a myriad of swap, price impact, and liquidity views. 

The most difficult, and unanswered, part of this will be building the historical liquidity data for v3 across ticks. We need to investigate both Dune and The Graph to see what our best options are here.

**Comment by deepsp94** [comment]
Thanks for the brief JD. :)

I'm starting with the 2 bullet points - using Uni v2 data on Dune. Will keep you in the loop about progress on this.

Once I have the above data, I'll spend some time today trying to figure the price impact calculation for v3.

**Comment by josephd8** [comment]
Uni v3 subgraph: https://thegraph.com/explorer/subgraph/benesjan/uniswap-v3-subgraph
Uni v2 subgraph: https://thegraph.com/explorer/subgraph/benesjan/uniswap-v2

**Comment by tgrecojs** [comment]
Just a heads up - going to put some research working in today on this task, specifically on the graph data. Reach out here or on discord if any ?s or info u think might be useful

**Comment by deepsp94** [comment]
For uniswap v2, working out price impact using pool reserves: https://duneanalytics.com/queries/61367
