### ISSUE TITLE
TWG Request 2021/06/28 - Treasury Assets per Index Token

### ISSUE THREAD

**Issue by jackiep00** [SetProtocol/index-coop-analytics#49]
From Matt:

Is there a way to do the following calc: 

Sum of USDC & DPI in USD terms dividend by qty of INDEX in circulating supply. Then a seperate calc, same numerator with total INDEX supply as the denominator
This metric would show hold much of the current INDEX price is essentially cash on hand

**Comment by josephd8** [comment]
@jackiep00 could we rename this issue so it is a bit more descriptive? Thanks!

**Comment by josephd8** [comment]
@jackiep00 moved this to "in progress"

**Comment by jackiep00** [comment]
Additional requests that I'm going to bundle in with this:
1. Can we create a price to sales ratio similar to nexus mutual for INDEX using total supply and then circulating supply?
a) Held INDEX (cumulative)
b) Hold INDEX - passive
c) Hold INDEX - via LP positions
d) Rate of change - 3 variables above on a daily/weekly basis
e) 7 day trading vol
f) 30 day trading vol
g) Standard deviation in token price against USD
h) Standard deviation in token price against ETH
i) Correlation coefficient INDEX to ETH over the last 90 days 
j) Correlation coefficient INDEX to ETH since genesis

asking for additional clarification

**Comment by jackiep00** [comment]
Another few requests:

1. From Madila:
May not be 100% treasury related but close enough so will post here.
Can we get a graph showing the value of $INDEX sat at the staking contracts over time? Maybe worth having a USD one and a unit one also showing flows.

My thinking here is if LM'ing is turned off / reduced, people may unstake their LP positions, therefore claiming the rewards. That's a fair bit of as of now illiquid Index potentially becoming liquid at once. Could be fun.

MVI
https://etherscan.io/tokenholdings?a=0x8f06FBA4684B5E0988F215a47775Bb611Af0F986
DPI v0.1
https://etherscan.io/tokenholdings?a=0x8f06FBA4684B5E0988F215a47775Bb611Af0F986
DPI v0.2
https://etherscan.io/tokenholdings?a=0xB93b505Ed567982E2b6756177ddD23ab5745f309

2.
From Matt:
are you able to predict forward when INDEX tokens are to be released from the year 2 and year 3 vesting contracts ?
I’d like to have a year 1, 2 and 3 vesting contract distribution all shown in a single chart. Like number of INDEX that comes available to the community per day

More details here:
https://github.com/SetProtocol/index-coop-smart-contracts/blob/master/contracts/token/Vesting.sol#L54

Total vesting amount *
(current timestamp - last time claim was called) / (vesting end time - vesting begin time)

e.g. 100 INDEX vesting over 1 year. Last time claimed: 1 week ago would be:

100 INDEX * 604800 seconds (1 week) / 31556926 seconds (1 year) = 1.916 claimable INDEX

I’m thinking a cumulative chart from 6/10/2020 through to 06/10/2023

3. Closing prices instead of average prices
we were looking at this query https://duneanalytics.com/queries/44939/127055 for month-end balances and noticed the price appears to be using an average of the price throughout the day by minute.  Could we use a midnight UTC price given we will primarily be using it for "closing the books" so to speak

**Comment by jackiep00** [comment]
more requests:
From Matt
4. Further to this @jackiepoo is it possible to look back through the staking contract, see what wallet address retrieved INDEX and then has a sell INDEX for ETH transaction within 48 hour window ? This would give us a ratio of portion of INDEX from LM sold on market upon being retrieved from LM staking contract

5. Is it possible to pick up the number of LP token in the MVI staking contract ?
Address: 0x5bc4249641b4bf4e37ef513f3fa5c63ecab34881
If we can create a chart showing the Qty of LP tokens staked in the contract, a cumulative and daily net change would be great data.
We can then create an APR chart which utilises the daily USD value of INDEX and the rate at which INDEX is being distributed. Distribution is 3,286 INDEX over 30 days, so like 109.53 INDEX per day

**Comment by jackiep00** [comment]
Once i get the Treasury Assets approved, I'll close this issue and organize these requests into new issues with priorities and complexity estimates and whatnot
