### ISSUE TITLE
MVI Rebalance Analytics

### ISSUE THREAD

**Issue by josephd8** [SetProtocol/index-coop-analytics#54]
The MVI methodologists (verto + dfc) are interested in analyzing the MVI rebalances to keep tabs on what tokens are problematic, how many trades each took, etc.

They have been manually pulling data from etherscan and transforming into excel (they have sent me that spreadsheet) to view the data as such:

![image](https://user-images.githubusercontent.com/17972458/124521106-a7d78e80-ddab-11eb-9956-9d5ff28eda77.png)

They are wondering if we can automate this analysis in Dune? If not, potentially using the Etherscan or other APIs?

**Comment by witwiki** [comment]
happy to look into this issue. Is there a technical architecture for the smart contracts I can look at to see how MVI works? Something like the FLI product: https://docs.google.com/presentation/d/1oQcuKkcyNWZ7nO-IqY-tk9h3Vb4_lktX0AyfEwdxDNs/edit#slide=id.gbc174a3cb8_0_42
That way I can determine if it can be done on Dune or use the Etherscan API.
