### ISSUE TITLE
TWG - High Priority - Medium Effort - Liquidity Mining Analysis - ETA 2021/07/22

### ISSUE THREAD

**Issue by jackiep00** [SetProtocol/index-coop-analytics#65]
There's lots of analyses to be done around whether or not liquidity mining is effective or not, which break down into a few questions:

1. How does farming APR affect flows into and out of liquidity pools?
2. How much INDEX is vulnerable to sudden liquidation if we end liquidity mining?
3. Of the people who are mining, what does the distribution look like? Are there a few large whales reaping the majority of the benefits?
4. Do liquidity miners liquidate their INDEX or hold it?

Broadly speaking, the question we are trying to answer is - is liquidity mining effective for us? If we end it, what are the consequences we are likely to experience?

Raw notes:

MVI
https://etherscan.io/tokenholdings?a=0x8f06FBA4684B5E0988F215a47775Bb611Af0F986
DPI v0.1
https://etherscan.io/tokenholdings?a=0x8f06FBA4684B5E0988F215a47775Bb611Af0F986
DPI v0.2
https://etherscan.io/tokenholdings?a=0xB93b505Ed567982E2b6756177ddD23ab5745f309

Further to this @jackiepoo is it possible to look back through the staking contract, see what wallet address retrieved INDEX and then has a sell INDEX for ETH transaction within 48 hour window ? This would give us a ratio of portion of INDEX from LM sold on market upon being retrieved from LM staking contract

Is it possible to pick up the number of LP token in the MVI staking contract ?
Address: 0x5bc4249641b4bf4e37ef513f3fa5c63ecab34881
If we can create a chart showing the Qty of LP tokens staked in the contract, a cumulative and daily net change would be great data.
We can then create an APR chart which utilises the daily USD value of INDEX and the rate at which INDEX is being distributed. Distribution is 3,286 INDEX over 30 days, so like 109.53 INDEX per day

**Comment by ripples3** [comment]
Commenting on this issue as instructed.
-Don | ETH to 10k#3452

**Comment by josephd8** [comment]
Thanks @ripples3 !

**Comment by jackiep00** [comment]
this should be linked to this pull request: https://github.com/SetProtocol/index-coop-analytics/pull/70

**Comment by josephd8** [comment]
linked @jackiep00 @ripples3

**Comment by jackiep00** [comment]
ok this is done, pending TWG approval:

LP TVL and APR over time here:  https://duneanalytics.com/queries/82789
Staker analysis here: https://duneanalytics.com/queries/87944

We should probably start a dashboard somewhere to show both off but I'd like to add DPI before doing that.

**Comment by josephd8** [comment]
@jackiep00 @ripples3 can we get something similar built out for DPI relatively quickly? I am assuming that we just need to swap some contract addresses around?

**Comment by josephd8** [comment]
It would be great to pump out the DPI as well and put them in a dashboard together as a foundation for Liquidity Mining analysis moving forward. How soon do you think we could get that up?

Awesome work on this @ripples3 & @jackiep00 !

**Comment by ripples3** [comment]
Hi @josephd8, I was in the TWG meeting yesterday. From what I heard, they will stop LM for DPI. I will clarify this to @jackiep00 or TWG if there is still a need.

**Comment by jackiep00** [comment]
Hmm the idea of leaving it half finished feels a bit bad. But I think it makes sense to just abandon this if the decision has already been made - no purpose in productizing it if no one needs it to help with their decision making

**Comment by josephd8** [comment]
@ripples3 @jackiep00 sorry I missed your comments here, I thought I had replied earlier - was just reviewing the PR. How much effort is required for DPI?
I, personally, would find it valuable to look at the historical liquidity mining program to see what we can glean from it. And it could be a good start for our next round of liquidity analytics.

If it is something that can be done rather quickly given the template already exists for MVI, I would say let's add DPI and then close this out. Let me know what you think!

**Comment by ripples3** [comment]
@josephd8, Not too much effort. I think a major difference is the INDEX emissions for each month. I am working on it. Hopefully, this can be completed within this day.

**Comment by ripples3** [comment]
LP TVL and APR over time: https://duneanalytics.com/queries/94971
Staker analysis: TBD

I need to open another PR so I can merge my work, right?

**Comment by josephd8** [comment]
@ripples3 ya if you could open up another PR similar to the MVI work that would be great! @jackiep00 can we just get these views added on a dashboard together? Then we can close all this out!
