### ISSUE TITLE
BTC2x-FLI Product Dashboard

### ISSUE THREAD

**Issue by Sidheartx** [SetProtocol/index-coop-analytics#68]
`BTC2x - Flexible Leverage Index`

```
**High Level KPIs** 
Address Exposure (current)
Unit Supply
Mint Volume (units & USD)
Trading Volume
Supply Breakdown
Daily Revenue
Cumulative Revenue
```
```
**`Cohort Retention (Review and improve on ETH2x first)`**

Holders Growth
Repeat Buyers
AUM
```

**`Trading Data `**

```
Buy & Sell Transactions
--
Buy & Sell Volume
```

More Info here - 
https://docs.google.com/spreadsheets/d/1mbJ7r0egq_DpJPgzMJU-GSzMMwQW6Tva1t6JHamZ6U4/edit?ts=60994032#gid=918329942

**Comment by jorijnsmit** [comment]
Confirming here that @Sidheartx and I agreed to me picking up (/porting from ETH2x):

- BTC vs BTC2x-FLI
- cWBTC / USDC debt / COMP Balance
- Leverage Ratio over time
- TWAP per trade

**Comment by Sidheartx** [comment]
Thanks for the help!

**Comment by josephd8** [comment]
Hey @Sidheartx - looking to close this one out. Do we have:

- [ ] the BTC2x Dash in your account that matches the ETH2x Dash (that also will be migrated to your account)

let me know when that is in place and we can get this closed out

**Comment by Sidheartx** [comment]
Yes, its in place 
https://dune.xyz/sidhemraj/BTC2x-FLI-Product-DashBoard

**Comment by Sidheartx** [comment]
Can close this one too @josephd8
