### ISSUE TITLE
DG2 voting

### ISSUE THREAD

**Issue by josephd8** [SetProtocol/index-coop-analytics#7]
We would like to understand **how** we got to the voting results in DG2 for these three products given that all had overwhelming majority FOR, although TTI did not pass while MVI and FLI did. The hypothesis is that a few large wallets allowed the MVI and FLI to pass, but the absence of a few whales in TTI was its killer.

What can we learn about the current voting power across INDEX?
What can we learn about the current state of governance at the Coop?

**Comment by josephd8** [comment]
@craigtutterow

**Comment by josephd8** [comment]
Data can be downloaded directly from snapshot: https://snapshot.org/#/index/closed
We will start with any "Decision Gate 2" votes - you should currently be able to download the MVI, TTI, and ETH2x-FLI DG2 votes. SDI and BTC2x-FLI DG2 voting should commence this week.

**Comment by craigtutterow** [comment]
Acknowledged, thanks!

**Comment by josephd8** [comment]
@craigtutterow we will want to include the recent DG2 votes on BTC2x-FLI and SMI. So I am thinking we build out a set of views and then replicate for each vote. I think we are particularly interested in answering the questions:

- How many voters did it take to reach quorum? So starting with the highest INDEX voter and moving down, how many until we reach ~220k. This could be something like a cumulative bar chart with a horizontal line at ~220k to see at how many voters the cumulative # of votes passes quorum.
- The opposite of ^. If we start at the lowest INDEX voters, how many would we have needed to reach quorum?

And then for all votes combined, it would be great to see:
- the distribution of holders participating in X votes (1-5 in this case).
- if possible, a gini coefficent (my best guess at a decentralization metric) for each vote on a line plot (maybe compared to a static benchmark that we can find?) 
-

**Comment by craigtutterow** [comment]
Initiated pull request with python scripts and notebook file: https://github.com/SetProtocol/index-coop-analytics/pull/25

This has Gini index and Lorenz curves of overall wallet balances, and balances of voters for each vote. Also computed the minimum number of voters needed to meet quorum in each vote.

From above comments, I've yet to look at the number of  votes needed to reach quorum if starting at the bottom of the distribution. Also haven't looked at voting participation across initiatives. Those should be straightforward tasks though.
