### ISSUE TITLE
FLI User Analytics

### ISSUE THREAD

**Issue by josephd8** [SetProtocol/index-coop-analytics#78]
set of metrics to go in FLI product dashboards (so will be implemented in both ETH2x and BTC2x) to better understand who is using the products and how they are using them

**Comment by josephd8** [comment]
@Sidheartx please comment so I can assign - thanks!

**Comment by Sidheartx** [comment]
Assign me here!

**Comment by Sidheartx** [comment]
@josephd8 assign me here. to be done this week, lets discuss

**Comment by josephd8** [comment]
@Sidheartx - want to move towards closing this out - do we have:

- [ ] these metrics included in the ETH2x dash
- [ ] the ETH2x dash migrated to your account

know you have been busy with other stuff, so no pressure, just want to get this closed out when we can

**Comment by Sidheartx** [comment]
This is done too @josephd8 
https://dune.xyz/sidhemraj/ETH2x-FLI-Product-Dashboard
https://dune.xyz/sidhemraj/BTC2x-FLI-Product-DashBoard

**Comment by Sidheartx** [comment]
Can close this one? @josephd8

**Comment by josephd8** [comment]
@Sidheartx is there a PR associated with this? I know we have the BTC2x dash PR, but should we also have one for ETH2x?

**Comment by Sidheartx** [comment]
Yeah, its all in the same PR for now.
