### ISSUE TITLE
Update ETH2x-FLI Cost Queries

### ISSUE THREAD

**Issue by josephd8** [SetProtocol/index-coop-analytics#79]
With BTC2x-FLI and ETH2x-FLI contracts being represented in the same tables in Dune now, we need to update the ETH2x-FLI cost queries to account for this change. The BTC2x-FLI cost queries will be build with this change already in place.

**Comment by josephd8** [comment]
@Sidheartx please comment so I can assign - thanks!

I would also say that if we can maybe prioritize this issue just so we know everything is working properly in the ETH2x-FLI dashboard, that would be great.

**Comment by Sidheartx** [comment]
Sure, I will prioritize these! BTC2x cost queries with all the relevant filtering are already in place.

**Comment by Sidheartx** [comment]
ETH2x Daily Revenue / Costs & ETH2x Cumulative Revenue/Costs/Profit updated via these two commits - 
https://github.com/SetProtocol/index-coop-analytics/pull/76/commits/361babe72b477460648728a86900ab3c5e6a48bf
https://github.com/SetProtocol/index-coop-analytics/pull/76/commits/21a03bc2a32aea2649907434ed84cb45dc0d3b1c

ETH2x Costs Breakdown pending

**Comment by Sidheartx** [comment]
@josephd8 I think the ETH2x Cohort retention query needs to be changed as well, need to add the Uniswap V3 bit

**Comment by josephd8** [comment]
@Sidheartx - so the costs decreased by 50% in the new query? 

And ya, the cohort retention will need to be fixed (along with a lot of other things) when the new exposure queries get finished.

**Comment by Sidheartx** [comment]
@josephd8 Costs on ETH2x FLI before submitting the BTC2x FLI contracts - Correct 
Costs on ETH2x FLI after BTC2x FLI contracts decoded - Almost Double 
Costs on ETH2x FLI after the above two filtering commits - Correct

**Comment by josephd8** [comment]
@Sidheartx Oh my bad must have read that wrong! Going to merge this and update those queries on the main dashboard!

**Comment by josephd8** [comment]
In the future, let's try to associate a PR to an issue, so for example the ETH2x cost updates should be committed to a new PR that we can attach to this issue!

**Comment by josephd8** [comment]
Actually, the Costs Breakdown is still WIP, ya @Sidheartx ? If so, lets get that updated and push a PR here and then that will close out this issue! Nice work!

**Comment by Sidheartx** [comment]
Yeah! Apologies for the mess. Will create separate branch PR for Issues. @josephd8

**Comment by josephd8** [comment]
Thank you!

**Comment by Sidheartx** [comment]
This is fixed. Can cost out this issue after reviewing the original PR. 
Commit for Revenue costs breakdown V2
https://github.com/Sidheartx/index-coop-analytics/commit/5ad860d3cd8d52e12718af6de4c1f36f11277523#diff-e3e9fd7725370cd11d81b2aeb485584392c4d40af7a53cecc532af53440dd3d7
