### ISSUE TITLE
Leverage Index Modeling

### ISSUE THREAD

**Issue by josephd8** [SetProtocol/index-coop-analytics#93]
Creating models for alternative leverage index approaches.

**Comment by josephd8** [comment]
@jackiep00 @sidheartx how do we want to treat this issue? Link to the sim sheet here and close it out for now? I am guessing there is upcoming work on this front, but thinking that we just create more granular issues as they come about..

**Comment by Sidheartx** [comment]
Yeah there's some upcoming work related to this which we will initiate this week. You can close this out - here's the link to the sheet https://docs.google.com/spreadsheets/d/18bkY6b0X8Y2Fp1ooghBBDHhaCSI0VvCfCu8JmHxvk9s/edit#gid=146197098
